### ISSUE TITLE
Support ModelAdmin.preserve_filters

### ISSUE THREAD

**Issue by smcoll** [edoburu/django-polymorphic-tree#23]
Regarding this property (introduced in Django 1.6): https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.preserve_filters

It seems that filter params are preserved through node creation until the final redirect to the changelist.  The "actions" buttons do not support the filter params at all.

**Comment by vdboor** [comment]
Most of this went into django-polymorphic directly. If you still see issues with the latest versions, please let me know. For now I'll be closing this ticket.
