### ISSUE TITLE
Python3/Django17: smart_unicode should be smart_text

### ISSUE THREAD

**Issue by DylanLukes** [edoburu/django-polymorphic-tree#30]
In `templatetags/stylable_admin_list.py` there is:

```python
...
from django.utils.encoding import smart_unicode, force_unicode
...
```

In Django 1.7 (and I believe 1.6) `smart_unicode` is replaced with `smart_text` under Python 3. In addition, `smart_text` is forwards compatible from Django 1.4.2 onward, so importing it under Python 2 should yield an alias to `smart_unicode`.

Source: https://docs.djangoproject.com/en/1.7/topics/python3/#string-handling

**Comment by vdboor** [comment]
Thanks, I've fixed this in 0afd88995061328f19cd53b46033013203b8381c
