### ISSUE TITLE
Django 1.8 fail example in admin. Django 1.7 OK.

### ISSUE THREAD

**Issue by stas630** [edoburu/django-polymorphic-tree#35]
I'm trying to upgrade django-polymorphic-tree/examaple to Django 1.8 and I notice an error that I don't have in 1.7  
http://127.0.0.1:8000/admin/tree/basetreenode/add/
Add Tree Node
Node type: Category node
Save
NoReverseMatch at /admin/tree/basetreenode/add/

Reverse for 'tree_basetreenode_change' with arguments '('__fk__',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['admin/tree/basetreenode/(\\d+)/$']

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/admin/tree/basetreenode/add/?ct_id=8
Django Version: 	1.8

**Comment by vdboor** [comment]
Thanks for reporting this! This is now fixed in django-polymorphic 0.7.1
