### ISSUE TITLE
incorrect BaseTreeNode.Meta in README?

### ISSUE THREAD

**Issue by smcoll** [edoburu/django-polymorphic-tree#39]
In the README example, shouldn't `BaseTreeNode.Meta` subclass `PolymorphicMPTTModel.Meta`, so the `ordering = ('tree_id', 'lft',)` declaration is preserved?

https://docs.djangoproject.com/en/1.8/topics/db/models/#meta-inheritance

**Comment by vdboor** [comment]
You're right! Fixed it.
