### ISSUE TITLE
method "do_move" Like django_mptt_admin/admin.py

### ISSUE THREAD

**Issue by stas630** [edoburu/django-polymorphic-tree#40]
To be able to restrict access to the moving node in the form PolymorphicMPTTParentModelAdmin need add method  "do_move" Like "django_mptt_admin/admin.py". In method api_node_moved_view after String " # TODO: with granular user permissions, check if user is allowed to edit both pages."

**Comment by vdboor** [comment]
Is there something I missed? I don't fully understand your question, nor why it is closed again..
