### ISSUE TITLE
Python 3.2 compatibility.

### ISSUE THREAD

**Issue by ixc-ops** [edoburu/django-polymorphic-tree#42]
Since Django still supports Python 3.2, is there anything `django-polymorphic-tree` absolutely *needs* from `future` (not compatible with Python 3.2) that isn't available in `six` (compatible with Python 3.2)?

Looks like only the following are being used: `with_metaclass`, `str`, `int`, `next`, `zip`. I'm not sure if these all have equivalents in `six`?

**Comment by vdboor** [comment]
The major issue with Python 3.2 is the lack of `u` prefix for strings.
Since Python 3.4 is already out, and 3.5 is around the corner, I wonder how relevant 3.2 support still is. Do you still need it?
