### ISSUE TITLE
Compatibility with django-polymorphic 0.8

### ISSUE THREAD

**Issue by fatal10110** [edoburu/django-polymorphic-tree#45]
From `django-polymorphic` changelog

```
BACKWARDS INCOMPATIBILITY: Removed __version__.py in favor of a standard __version__ in polymorphic/__init__.py.
```

but here
https://github.com/edoburu/django-polymorphic-tree/blob/master/polymorphic_tree/admin/parentadmin.py#L9

```
from polymorphic.__version__ import __version__ as polymorphic_version
```

**Comment by vdboor** [comment]
Wow, that was fast :)

I was testing the code today on it, you can enjoy the new 1.2 release.
